/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Food extends javax.swing.JFrame {

    /**
     * Creates new form Food
     */
    public Food() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Food_Name = new javax.swing.JTextField();
        Home_Delivery_Name = new javax.swing.JTextField();
        Tax_Name = new javax.swing.JTextField();
        Drink_Name = new javax.swing.JTextField();
        Food_Price = new javax.swing.JTextField();
        Home_Delivery_Price = new javax.swing.JTextField();
        Drink_Price = new javax.swing.JTextField();
        Tax_Price = new javax.swing.JTextField();
        ADD = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Area = new javax.swing.JTextArea();
        Receipt = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Registration_Page = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel1.setText("                       BILL RECEIPT PRINTING SYSTEM");

        jLabel2.setText("   PRODUCT PRICE");

        jLabel3.setText("            FOOD");

        jLabel4.setText("   PRODUCT NAME");

        jLabel5.setText("            DRINK");

        jLabel6.setText("              TAX");

        jLabel7.setText("   HOME DELIVERY");

        Food_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Food_NameActionPerformed(evt);
            }
        });

        Home_Delivery_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_Delivery_NameActionPerformed(evt);
            }
        });

        Tax_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tax_NameActionPerformed(evt);
            }
        });

        Drink_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Drink_NameActionPerformed(evt);
            }
        });

        Food_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Food_PriceActionPerformed(evt);
            }
        });

        Home_Delivery_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_Delivery_PriceActionPerformed(evt);
            }
        });

        Drink_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Drink_PriceActionPerformed(evt);
            }
        });

        Tax_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tax_PriceActionPerformed(evt);
            }
        });

        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        Reset.setText("RESET");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Area.setColumns(20);
        Area.setRows(5);
        jScrollPane1.setViewportView(Area);

        Receipt.setText("RECEIPT");
        Receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiptActionPerformed(evt);
            }
        });

        Registration_Page.setText("Registration_Page");
        Registration_Page.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Registration_PageMouseClicked(evt);
            }
        });
        jMenuBar1.add(Registration_Page);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Home_Delivery_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Home_Delivery_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Tax_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Tax_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Drink_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Drink_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Food_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Food_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(54, 54, 54))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Food_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Food_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Drink_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Drink_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tax_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tax_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Home_Delivery_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Home_Delivery_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Receipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(16, 16, 16))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Food_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Food_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Food_NameActionPerformed

    private void Home_Delivery_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_Delivery_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Home_Delivery_NameActionPerformed

    private void Tax_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tax_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tax_NameActionPerformed

    private void Drink_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Drink_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Drink_NameActionPerformed

    private void Food_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Food_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Food_PriceActionPerformed

    private void Home_Delivery_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_Delivery_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Home_Delivery_PriceActionPerformed

    private void Drink_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Drink_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Drink_PriceActionPerformed

    private void Tax_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tax_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tax_PriceActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Room_Details rd = new Room_Details();
        rd.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        Food_Name.setText("");
        Food_Price.setText("");
        Drink_Name.setText("");
        Drink_Price.setText("");
        Tax_Name.setText("");
        Tax_Price.setText("");
        Home_Delivery_Name.setText("");
        Home_Delivery_Price.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        // TODO add your handling code here:
        if(Food_Name.getText().length()<=0)
        {
            JOptionPane.showMessageDialog(null, "Please Fill Food Name");
        }
        else if(Food_Price.getText().length()<=0)
        {
            JOptionPane.showMessageDialog(null, "Please Fill Food Price");
        }
        else if(Drink_Name.getText().length()<=0)
        {
            JOptionPane.showMessageDialog(null, "Please Fill Drink Name");
        }
        else if(Drink_Price.getText().length()<=0)
        {
            JOptionPane.showMessageDialog(null, "Please Fill Drink Price");
        }
        else if(Tax_Name.getText().length()<=0)
        {
            JOptionPane.showMessageDialog(null, "Please Fill Tax Name");
        }
        else if(Tax_Price.getText().length()<=0)
        {
            JOptionPane.showMessageDialog(null, "Please Fill Tax Price");
        }
        else if(Home_Delivery_Name.getText().length()<=0)
        {
            JOptionPane.showMessageDialog(null, "Please Fill Home Delivery Name");
        }
        else if(Home_Delivery_Price.getText().length()<=0)
        {
            JOptionPane.showMessageDialog(null, "Please Fill Home Delivery Price");
        }
        else if(Food_Name.getText().length()<=0 && Food_Price.getText().length()<=0 &&
                Drink_Name.getText().length()<=0 && Drink_Price.getText().length()<=0 &&
                Tax_Name.getText().length()<=0 && Tax_Price.getText().length()<=0 &&
                Home_Delivery_Name.getText().length()<=0 && Home_Delivery_Price.getText().length()<=0)
        {
            JOptionPane.showMessageDialog(null, "Please Fill All Fields");
        }
        else
        {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/logindata","root","root");
            String sql = "insert into food_details(Food_Name,Food_Price,Drink_Name,Drink_Price,Tax_Name,Tax_Price,Home_Delivery_Name,Home_Delivery_Price) values(?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, Food_Name.getText());
            pst.setInt(2, Integer.parseInt(Food_Price.getText()));
            pst.setString(3, Drink_Name.getText());
            pst.setInt(4, Integer.parseInt(Drink_Price.getText()));
            pst.setString(5, Tax_Name.getText());
            pst.setInt(6, Integer.parseInt(Tax_Price.getText()));
            pst.setString(7, Home_Delivery_Name.getText());
            pst.setInt(8, Integer.parseInt(Home_Delivery_Price.getText()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Food Data Inserted");
            Area.setText("**********************************************\n");
            Area.setText(Area.getText()+"Receipt");
            Area.setText(Area.getText()+"**************************************\n");
            Area.setText(Area.getText()+"Food_Name :-  "+Food_Name.getText()+"\n");
            Area.setText(Area.getText()+"Food_Price :-  "+Food_Price.getText()+"\n");
            Area.setText(Area.getText()+"Drink_Name :-  "+Drink_Name.getText()+"\n");
            Area.setText(Area.getText()+"Drink_Price :-  "+Drink_Price.getText()+"\n");
            Area.setText(Area.getText()+"Tax_Name :-  "+Tax_Name.getText()+"\n");
            Area.setText(Area.getText()+"Tax_Price :-  "+Tax_Price.getText()+"\n");
            Area.setText(Area.getText()+"Home_Delivery_Price :-  "+Home_Delivery_Name.getText()+"\n");
            Area.setText(Area.getText()+"Home_Delivery_Price :-  "+Home_Delivery_Price.getText()+"\n");
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_ADDActionPerformed

    private void ReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiptActionPerformed
        // TODO add your handling code here:
        if(Food_Name.getText().length()<=0 && Food_Price.getText().length()<=0 &&
                Drink_Name.getText().length()<=0 && Drink_Price.getText().length()<=0 &&
                Tax_Name.getText().length()<=0 && Tax_Price.getText().length()<=0 &&
                Home_Delivery_Name.getText().length()<=0 && Home_Delivery_Price.getText().length()<=0)
        {
            JOptionPane.showMessageDialog(null, "Please Fill All Fields");
        }
        else
        {
        try
        {
            Area.print();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_ReceiptActionPerformed

    private void Registration_PageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Registration_PageMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        Registration_Page reg = new Registration_Page();
        reg.setVisible(true);
    }//GEN-LAST:event_Registration_PageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Food().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JTextArea Area;
    private javax.swing.JButton Back;
    private javax.swing.JTextField Drink_Name;
    private javax.swing.JTextField Drink_Price;
    private javax.swing.JTextField Food_Name;
    private javax.swing.JTextField Food_Price;
    private javax.swing.JTextField Home_Delivery_Name;
    private javax.swing.JTextField Home_Delivery_Price;
    private javax.swing.JButton Receipt;
    private javax.swing.JMenu Registration_Page;
    private javax.swing.JButton Reset;
    private javax.swing.JTextField Tax_Name;
    private javax.swing.JTextField Tax_Price;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
